// Generated by scripts/generate_integration_sdks.py; do not edit.
// Structural hints only: validate at runtime for semantic constraints.
export type JsonValue = null | boolean | number | string | JsonValue[]
  | { [key: string]: JsonValue };

export interface ArtifactReceiptContract {
  artifact_kind: string;
  artifact_metadata?: Record<string, JsonValue>;
  content_sha256: string;
  contract_type: "artifact_receipt";
  external_receipt_id: string;
  mime_type: string;
  original_filename?: string | null;
  receipt_metadata?: Record<string, JsonValue>;
  received_at: string;
  schema_version: "1";
  sender?: ExternalActorRef | null;
  size_bytes: number;
  source: IntegrationSource;
  storage_provider: string;
  storage_reference: string;
  tenant_id: string;
}

export interface CapabilityInvocationContract {
  capability: string;
  causation_id?: string | null;
  confidence?: "high" | "medium" | "low";
  contract_type: "capability_invocation";
  correlation_id: string;
  idempotency_key: string;
  integration: IntegrationSource;
  metadata_sanitized?: Record<string, JsonValue>;
  parameters?: Record<string, JsonValue>;
  resource?: Record<string, JsonValue> | null;
  schema_version: "1";
  target?: Record<string, JsonValue> | null;
  tenant_id: string;
  user_requested?: boolean;
}

export interface ChannelDeliveryContract {
  artifact_ids?: Array<string>;
  causation_id?: string | null;
  contract_type: "channel_delivery";
  correlation_id: string;
  idempotency_key: string;
  integration: IntegrationSource;
  metadata_sanitized?: Record<string, JsonValue>;
  payload_ref?: Record<string, JsonValue>;
  payload_type: string;
  schema_version: "1";
  target_binding_id: string;
  tenant_id: string;
}

export interface ExternalActorRef {
  display_name?: string | null;
  external_actor_id: string;
}

export interface ExternalThreadRef {
  external_thread_id: string;
  kind?: IntegrationThreadKind;
  title?: string | null;
}

export interface InboundIntegrationEvent {
  actor?: ExternalActorRef | null;
  artifact_ids?: Array<string>;
  causation_id?: string | null;
  contract_type: "inbound_event";
  correlation_id: string;
  event_type: string;
  external_event_id: string;
  idempotency_key: string;
  metadata_sanitized?: Record<string, JsonValue>;
  occurred_at: string;
  payload_ref?: Record<string, JsonValue>;
  payload_type: string;
  received_at: string;
  schema_version: "1";
  source: IntegrationSource;
  tenant_id: string;
  thread?: ExternalThreadRef | null;
}

export type IntegrationErrorClass = "AUTHENTICATION" | "AUTHORIZATION" | "RATE_LIMIT" | "TIMEOUT" | "PROVIDER_UNAVAILABLE" | "INVALID_REQUEST" | "NOT_FOUND" | "CONFLICT" | "UNKNOWN";

export type IntegrationKind = "CHANNEL" | "CAPABILITY";

export interface IntegrationResultContract {
  contract_type: "integration_result";
  correlation_id: string;
  details_sanitized?: Record<string, JsonValue>;
  error_class?: IntegrationErrorClass | null;
  integration: IntegrationSource;
  provider_reference?: string | null;
  reason_code: string;
  request_id: string;
  retry_after_seconds?: number | null;
  schema_version: "1";
  status: IntegrationResultStatus;
  tenant_id: string;
}

export type IntegrationResultStatus = "SUCCEEDED" | "ACCEPTED" | "RETRYABLE_FAILURE" | "PERMANENT_FAILURE";

export interface IntegrationSource {
  account_id?: string | null;
  instance_id: string;
  kind: IntegrationKind;
  name: string;
}

export type IntegrationThreadKind = "DIRECT" | "GROUP" | "THREAD" | "CHANNEL";

export type IntegrationContractMessage =
    ArtifactReceiptContract
    | InboundIntegrationEvent
    | ChannelDeliveryContract
    | CapabilityInvocationContract
    | IntegrationResultContract
;
