UserParameter=andy.docker.inventory,/usr/bin/python3 /usr/local/lib/andy-docker-view/zabbix_inventory.py
UserParameter=andy.docker.inventory.containers,/usr/bin/python3 /usr/local/lib/andy-docker-view/zabbix_inventory.py containers
UserParameter=andy.docker.inventory.container_labels,/usr/bin/python3 /usr/local/lib/andy-docker-view/zabbix_inventory.py container_labels
UserParameter=andy.docker.inventory.networks,/usr/bin/python3 /usr/local/lib/andy-docker-view/zabbix_inventory.py networks
UserParameter=andy.docker.inventory.attachments,/usr/bin/python3 /usr/local/lib/andy-docker-view/zabbix_inventory.py attachments
UserParameter=andy.docker.inventory.ports,/usr/bin/python3 /usr/local/lib/andy-docker-view/zabbix_inventory.py ports
