"""Generate SDK structural types and bundle the canonical wire schema, without core imports."""

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "contracts/integration/v1/integration-contract.schema.json"
PYTHON = ROOT / "sdks/python/src/andy_integration_sdk"
TYPESCRIPT = ROOT / "sdks/typescript/src"


def type_expression(node: dict, language: str) -> str:
    if "$ref" in node:
        prefix = "#/$defs/"
        if not node["$ref"].startswith(prefix):
            raise ValueError("SDK types only support local definition references")
        # Refinements (patterns, roles, conditionals) are enforced by the bundled schema.
        return node["$ref"][len(prefix):]
    if "const" in node or "enum" in node:
        values = [node["const"]] if "const" in node else node["enum"]
        if not all(isinstance(value, str) for value in values):
            raise ValueError("Expected string literals in integration contract")
        literals = ", ".join(repr(value) for value in values)
        return f"Literal[{literals}]" if language == "python" else " | ".join(
            json.dumps(value) for value in values
        )
    for union in ("anyOf", "oneOf"):
        if union in node:
            return " | ".join(type_expression(item, language) for item in node[union])
    kind = node.get("type")
    primitives = {
        "python": {"string": "str", "integer": "int | float", "number": "int | float",
                   "boolean": "bool", "null": "None"},
        "typescript": {"string": "string", "integer": "number", "number": "number",
                       "boolean": "boolean", "null": "null"},
    }
    if kind in primitives[language]:
        return primitives[language][kind]
    if kind == "array":
        item = type_expression(node["items"], language)
        return f"list[{item}]" if language == "python" else f"Array<{item}>"
    if kind == "object" and not node.get("properties") and node.get("additionalProperties") is True:
        return "dict[str, JsonValue]" if language == "python" else "Record<string, JsonValue>"
    raise ValueError(f"Unsupported structural schema shape: {node}")


def render_types(schema: dict, language: str) -> str:
    if language == "python":
        lines = [
            '"""Generated by scripts/generate_integration_sdks.py; do not edit.',
            "Structural hints only: validate at runtime for semantic constraints.",
            '"""', "", "from __future__ import annotations", "",
            "from typing import Literal, Required, TypedDict, Union", "",
            'JsonValue = Union[None, bool, int, float, str, list["JsonValue"],',
            '                  dict[str, "JsonValue"]]',
        ]
    else:
        lines = [
            "// Generated by scripts/generate_integration_sdks.py; do not edit.",
            "// Structural hints only: validate at runtime for semantic constraints.",
            "export type JsonValue = null | boolean | number | string | JsonValue[]",
            "  | { [key: string]: JsonValue };",
        ]
    for name, node in schema["$defs"].items():
        if not name.isidentifier():
            raise ValueError(f"Invalid definition identifier: {name}")
        lines.extend(["", ""] if language == "python" else [""])
        if "properties" not in node:
            expression = type_expression(node, language)
            lines.append(f"{name} = {expression}" if language == "python"
                         else f"export type {name} = {expression};")
            continue
        if node.get("additionalProperties") is not False:
            raise ValueError("Named contract objects must explicitly close extra properties")
        required = node.get("required", [])
        lines.append(f"class {name}(TypedDict, total=False):" if language == "python"
                     else f"export interface {name} {{")
        for field, property_schema in node["properties"].items():
            if not field.isidentifier():
                raise ValueError(f"Invalid property identifier: {field}")
            expression = type_expression(property_schema, language)
            if language == "python":
                hint = f"Required[{expression}]" if field in required else expression
                lines.append(f"    {field}: {hint}")
            else:
                optional = "" if field in required else "?"
                lines.append(f"  {field}{optional}: {expression};")
        if language == "typescript":
            lines.append("}")
    members = [type_expression(item, language) for item in schema["oneOf"]]
    lines.extend(["", "IntegrationContractMessage = (" if language == "python"
                  else "export type IntegrationContractMessage ="])
    lines.extend(f"    {'| ' if i else ''}{member}" for i, member in enumerate(members))
    lines.append(")" if language == "python" else ";")
    if language == "python":
        lines.extend(["", "__all__ = [", '    "JsonValue", "IntegrationContractMessage",'])
        lines.extend(f'    "{name}",' for name in schema["$defs"])
        lines.append("]")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail on generated-file drift")
    args = parser.parse_args()
    raw = SCHEMA_PATH.read_bytes()
    schema = json.loads(raw)
    outputs = {
        PYTHON / "_schema.json": raw,
        TYPESCRIPT / "_schema.json": raw,
        PYTHON / "_types.py": render_types(schema, "python").encode(),
        TYPESCRIPT / "types.ts": render_types(schema, "typescript").encode(),
        ROOT / "sdks/python/LICENSE": (ROOT / "LICENSE").read_bytes(),
        ROOT / "sdks/typescript/LICENSE": (ROOT / "LICENSE").read_bytes(),
    }
    stale = []
    for path, content in outputs.items():
        if args.check:
            if not path.exists() or path.read_bytes() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)
    if stale:
        print("SDK generated files are stale; run python scripts/generate_integration_sdks.py")
        print("\n".join(stale))
        return 1
    print(f"SDK generated files {'checked' if args.check else 'updated'}: {len(outputs)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
