"""Generated by scripts/generate_integration_sdks.py; do not edit.
Structural hints only: validate at runtime for semantic constraints.
"""

from __future__ import annotations

from typing import Literal, Required, TypedDict, Union

JsonValue = Union[None, bool, int, float, str, list["JsonValue"],
                  dict[str, "JsonValue"]]


class ArtifactReceiptContract(TypedDict, total=False):
    artifact_kind: Required[str]
    artifact_metadata: dict[str, JsonValue]
    content_sha256: Required[str]
    contract_type: Required[Literal['artifact_receipt']]
    external_receipt_id: Required[str]
    mime_type: Required[str]
    original_filename: str | None
    receipt_metadata: dict[str, JsonValue]
    received_at: Required[str]
    schema_version: Required[Literal['1']]
    sender: ExternalActorRef | None
    size_bytes: Required[int | float]
    source: Required[IntegrationSource]
    storage_provider: Required[str]
    storage_reference: Required[str]
    tenant_id: Required[str]


class CapabilityInvocationContract(TypedDict, total=False):
    capability: Required[str]
    causation_id: str | None
    confidence: Literal['high', 'medium', 'low']
    contract_type: Required[Literal['capability_invocation']]
    correlation_id: Required[str]
    idempotency_key: Required[str]
    integration: Required[IntegrationSource]
    metadata_sanitized: dict[str, JsonValue]
    parameters: dict[str, JsonValue]
    resource: dict[str, JsonValue] | None
    schema_version: Required[Literal['1']]
    target: dict[str, JsonValue] | None
    tenant_id: Required[str]
    user_requested: bool


class ChannelDeliveryContract(TypedDict, total=False):
    artifact_ids: list[str]
    causation_id: str | None
    contract_type: Required[Literal['channel_delivery']]
    correlation_id: Required[str]
    idempotency_key: Required[str]
    integration: Required[IntegrationSource]
    metadata_sanitized: dict[str, JsonValue]
    payload_ref: dict[str, JsonValue]
    payload_type: Required[str]
    schema_version: Required[Literal['1']]
    target_binding_id: Required[str]
    tenant_id: Required[str]


class ExternalActorRef(TypedDict, total=False):
    display_name: str | None
    external_actor_id: Required[str]


class ExternalThreadRef(TypedDict, total=False):
    external_thread_id: Required[str]
    kind: IntegrationThreadKind
    title: str | None


class InboundIntegrationEvent(TypedDict, total=False):
    actor: ExternalActorRef | None
    artifact_ids: list[str]
    causation_id: str | None
    contract_type: Required[Literal['inbound_event']]
    correlation_id: Required[str]
    event_type: Required[str]
    external_event_id: Required[str]
    idempotency_key: Required[str]
    metadata_sanitized: dict[str, JsonValue]
    occurred_at: Required[str]
    payload_ref: dict[str, JsonValue]
    payload_type: Required[str]
    received_at: Required[str]
    schema_version: Required[Literal['1']]
    source: Required[IntegrationSource]
    tenant_id: Required[str]
    thread: ExternalThreadRef | None


IntegrationErrorClass = Literal['AUTHENTICATION', 'AUTHORIZATION', 'RATE_LIMIT', 'TIMEOUT', 'PROVIDER_UNAVAILABLE', 'INVALID_REQUEST', 'NOT_FOUND', 'CONFLICT', 'UNKNOWN']


IntegrationKind = Literal['CHANNEL', 'CAPABILITY']


class IntegrationResultContract(TypedDict, total=False):
    contract_type: Required[Literal['integration_result']]
    correlation_id: Required[str]
    details_sanitized: dict[str, JsonValue]
    error_class: IntegrationErrorClass | None
    integration: Required[IntegrationSource]
    provider_reference: str | None
    reason_code: Required[str]
    request_id: Required[str]
    retry_after_seconds: int | float | None
    schema_version: Required[Literal['1']]
    status: Required[IntegrationResultStatus]
    tenant_id: Required[str]


IntegrationResultStatus = Literal['SUCCEEDED', 'ACCEPTED', 'RETRYABLE_FAILURE', 'PERMANENT_FAILURE']


class IntegrationSource(TypedDict, total=False):
    account_id: str | None
    instance_id: Required[str]
    kind: Required[IntegrationKind]
    name: Required[str]


IntegrationThreadKind = Literal['DIRECT', 'GROUP', 'THREAD', 'CHANNEL']

IntegrationContractMessage = (
    ArtifactReceiptContract
    | InboundIntegrationEvent
    | ChannelDeliveryContract
    | CapabilityInvocationContract
    | IntegrationResultContract
)

__all__ = [
    "JsonValue", "IntegrationContractMessage",
    "ArtifactReceiptContract",
    "CapabilityInvocationContract",
    "ChannelDeliveryContract",
    "ExternalActorRef",
    "ExternalThreadRef",
    "InboundIntegrationEvent",
    "IntegrationErrorClass",
    "IntegrationKind",
    "IntegrationResultContract",
    "IntegrationResultStatus",
    "IntegrationSource",
    "IntegrationThreadKind",
]
