from enum import StrEnum


class InteractionState(StrEnum):
    RECEIVED = "RECEIVED"
    WAITING = "WAITING"
    DECIDING = "DECIDING"
    ACTING = "ACTING"
    WAITING_ACK = "WAITING_ACK"
    ESCALATING = "ESCALATING"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    CANCELED_BY_HUMAN_REPLY = "CANCELED_BY_HUMAN_REPLY"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class ActionState(StrEnum):
    REQUESTED = "REQUESTED"
    DISPATCHED = "DISPATCHED"
    EXECUTED = "EXECUTED"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    FAILED = "FAILED"


class TimerKind(StrEnum):
    ACTION_ACK_TIMEOUT = "ACTION_ACK_TIMEOUT"
    INITIAL_WAIT = "INITIAL_WAIT"

